### ISSUE TITLE
Request time

### ISSUE THREAD

**Issue by Fathonizep** [TheresAFewConors/Sooty#16]
Hello, I tried to make a file that contains hash list. I make a some modification for list.txt input. I have a purpose for match hash list with vt hash signature to decide its malware or not line by line. But the problem is, that it takes a very long time for giving the result. I am new in programming, so i dont know whats wrong with that. Sorry I'm not fluent in English, i hope u understand what im saying. is there any solution?

**Comment by TheresAFewConors** [comment]
Hi Fathonizep,

Currently Sooty does not have the functionality to process entire lists of hashes at once (Batch input) partly due to being limited to 4 requests per minute by VirusTotal. The way that is has been scripted is to simply do one check and move on - if you want to upload your modified code to pastebin and leave a link here I'll take a look and see if there's anything I can see to fix the issue.

**Comment by Fathonizep** [comment]
Im sorry its my mistake. The request takes so long because of my internet connection. I tried to run the script on my vps and its running pretty good. So this issues is closed. Thanks

**Comment by TheresAFewConors** [comment]
Glad to hear you got it working.

I'm trying to do some bug fixes and then the next update will be based around batch input and output, with a somewhat nice layout for the output.

Those premium VT keys are very handy! If you have any other issues with Sooty feel free to open another case - I'll try and respond as soon as I can
