### ISSUE TITLE
Non-ASCII character

### ISSUE THREAD

**Issue by aki2419** [TheresAFewConors/Sooty#37]
When trying to launch Sooty, getting the below error.

python Sooty.py
  File "Sooty.py", line 822
SyntaxError: Non-ASCII character '\xe2' in file Sooty.py on line 822, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by naveci** [comment]
@TheresAFewConors 
Adding `# coding: utf-8` to the top of the file might help
Otherwise, changing that dot to a simple minus-sign should fix it as well.

The latter might be preferable.

**Comment by TheresAFewConors** [comment]
Hi @aki2419 Thanks for creating this ticket to tracker the issue. I have updated the code so if you want to redownload Sooty it should solve the issue you had.

For documentation:
The bug was caused on line 822: `      print('     • %s' % each)`, replacing the bullet point with a hyphen solved this issue.

@naveci Same idea I had, simply add a hyphen! Thanks for the input!

**Comment by aki2419** [comment]
@TheresAFewConors Yes, that solved the issue after I had made some changes. Since i was python 3.x i had to change from library names as well then it worked out great. You might want to change the bullet points at these locations as well. From 930 till 944, 960,963,966,977,970,971,974

**Comment by naveci** [comment]
put a fix for the other characters in a PR. 
@aki2419 I'm also running Python 3. 3.7 to be exact. What's not working and what is your exact version?

**Comment by aki2419** [comment]
@naveci I am using 3.6 version of Python. As of now everything is working after I had changed the import modules name and removed the bullet points e.g. HTMLParser to html.parser, urllib.parser to url.parser. etc..
