### ISSUE TITLE
Debug errors in BadIP APi 

### ISSUE THREAD

**Issue by nitin-techie** [TheresAFewConors/Sooty#56]
**What is the feature that you are requesting?**
1.) The BadIP API returns "IP Not Found" even for some IPs present in the BadIP DB, i would work on the code to make it full-proof.

**Additional information**
- ...
- ...

**Is your feature request related to a problem? Please describe.**
BadIP is making decision based on just 1 category listed for the IOC.
Customize the code to consider all the categories marked and display result.

**Additional context**

**Comment by TheresAFewConors** [comment]
@nitin-techie Thanks for spotting an error in the BadIP DB output. It has been some time since you opened this issue however if you are still wanting to work on this fix I will assign it to you.

Direct output to txt would be a nice to have and better than the current method of piping Sooty into a file also.

**Comment by nitin-techie** [comment]
@TheresAFewConors -- Thanks for the acknowledgement.
Please assign it, and i will begin to work on this.

**Comment by TheresAFewConors** [comment]
@nitin-techie assigned to you now.

**Comment by nitin-techie** [comment]
@TheresAFewConors -- Hi, its done. Pls Review.
